### ISSUE TITLE
RANT

### ISSUE THREAD

**Issue by OakUnicycle** [randombanana9/NEA#1]
WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by randombanana9** [comment]
Works on my machine, closed.
